### ISSUE TITLE
Library is completely broken?

### ISSUE THREAD

**Issue by adamjstewart** [brianhelba/zipfile-deflate64#19] opened 2021-12-14 04:17 UTC
This library doesn't seem to be able to extract any deflate64 files.

### Steps to reproduce

```console
$ wget https://github.com/brianhelba/zipfile-deflate64/raw/master/tests/data/deflate64.zip
$ python
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipfile_deflate64 as zipfile
>>> with zipfile.ZipFile('deflate64.zip') as f:
...     f.extractall()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/anaconda/envs/torchgeo/lib/python3.9/zipfile.py", line 1633, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/anaconda/envs/torchgeo/lib/python3.9/zipfile.py", line 1688, in _extract_member
    shutil.copyfileobj(source, target)
  File "/anaconda/envs/torchgeo/lib/python3.9/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/anaconda/envs/torchgeo/lib/python3.9/zipfile.py", line 922, in read
    data = self._read1(n)
  File "/anaconda/envs/torchgeo/lib/python3.9/zipfile.py", line 1005, in _read1
    data = self._decompressor.decompress(data)
ValueError: Bad Deflate64 data: invalid block type
```
Note that the same file can be extracted using `unzip`, so the file is not corrupted:
```console
$ unzip deflate64.zip 
Archive:  deflate64.zip
  inflating: 100_lines.txt           
  inflating: 100k_lines.txt          
  inflating: 10_lines.txt            
  inflating: 10k_lines.txt           
```

### Environment

* Ubuntu 18.04
* Python 3.9.7 (installed with conda)
* zipfile-deflate64 0.1.6 (installed with pip)

**Comment by adamjstewart** [comment] 2021-12-14 04:33
P.S. How did you create https://github.com/brianhelba/zipfile-deflate64/blob/master/tests/data/deflate64.zip? I want to do something similar in my unit tests.

**Comment by adamjstewart** [comment] 2021-12-14 05:36
EDIT: now I'm trying again and an installation from a wheel is also failing with this error message. Maybe this is just a bug in the library?

**Comment by brianhelba** [comment] 2022-01-05 09:01
@adamjstewart Thanks to a series of patches from @cielavenir , this is now fixed. I'm issuing a new PyPI release now.

**Closed** 2022-01-05 09:00 UTC

**Comment by adamjstewart** [comment] 2022-01-05 15:41
Thanks @brianhelba and @cielavenir, it seems to be working now! Out of curiosity, how did you create the https://github.com/brianhelba/zipfile-deflate64/raw/master/tests/data/deflate64.zip file? I would like to create a deflate64 file for testing my own library but I haven't yet figured out how to create one on macOS/Linux.

**Comment by brianhelba** [comment] 2022-01-05 21:07
@adamjstewart I used [the `p7zip` CLI](https://wiki.archlinux.org/title/p7zip) as: `7z a deflate64.zip -mm=DEFLATE64 10_lines.txt` to create the test ZIP file. I should probably commit my script for doing that. :smiley:

**Comment by adamjstewart** [comment] 2022-01-05 21:58
Is this library (zipfile-deflate64) capable of writing deflate64 (not just reading)? If not, are there any plans to add write support? The 7z command will work for me for testing, but if I want to generate files on the fly I doubt that would work cross-platform.

**Comment by brianhelba** [comment] 2022-01-05 23:47
@adamjstewart I'll answer in a new issue, since we're moving out of scope of this one.

**Comment by cielavenir** [comment] 2022-01-06 00:43
btw I suppose 7z command is cross-platform if it includes p7zip.

**Comment by brianhelba** [comment] 2022-01-06 22:35
> btw I suppose 7z command is cross-platform if it includes p7zip.

@cielavenir @adamjstewart I'm not exactly sure what you mean by this. However:
* [The 7zip project](https://www.7-zip.org/) and [the p7zip project](http://p7zip.sourceforge.net/) are separate codebases.
* 7zip is Windows-only.
* p7zip is POSIX-only (Linux and MacOS).
* p7zip typically installs a binary called `7z`, to provide its CLI.

For more detail, I've tried to outline some of the state of the ecosystem here: https://github.com/brianhelba/zipfile-deflate64#the-problem .

**Comment by cielavenir** [comment] 2022-01-07 02:01
- 7z.exe CLI (in 7zNNNN-x64.exe distribution) and p7zip 7z has the same command-line syntax.
- 7zz (Igor's 7z for macOS/Linux) has the same codebase and has the same command-line syntax.
- `p7zip does not build an API for external software to invoke for decompression.` I don't understand this, https://github.com/cielavenir/mini7z/blob/master/lib/lzmasdk.c is usable for both 7z.dll and p7zip 7z.so.
- (minor) I can suggest Deflate64 support on py7zr via zipfile-deflate64 0.2.0.

**Comment by cielavenir** [comment] 2022-01-07 10:44
updated mini7z; confirmed that it can extract PKImploded zip with https://github.com/cielavenir/p7zip/tree/blast/CPP/7zip/Compress/PKImplode copied (I mean my codec is loaded by 7z.so which is loaded by mini7z). this is not possible if "p7zip does not build an API".

**Comment by cielavenir** [comment] 2022-01-07 10:47
maybe, for "cross-platform", what I need to emphasize is that 7z.dll and p7zip 7z.so APIs are the same although they have separate codebase.

**Comment by cielavenir** [comment] 2022-01-07 14:15
@brianhelba suggested Deflate64 decoder https://github.com/miurahr/py7zr/pull/399
